name: practical-bayes-env
channels:
  - conda-forge
dependencies:
  - pytensor
  - arviz
  - jupyter
  - jupyterlab
  - matplotlib
  - numpy
  - pandas<2.0
  - pip
  - pymc>=5.8
  - python-graphviz
  - scikit-learn
  - scipy
  - seaborn
  - watermark
